version: "3"
services:
  data-layer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "80:80"
    volumes:
      - ./server:/app  # Mount the local app directory to /app in the container
      - /mnt/datasets/vbs/:/data/vbs/
